apiVersion: shop.shophub.io/v1alpha1
kind: DiscordChannel
metadata:
  name: clothing-shop-notifications
  namespace: default
spec:
  guildID: "1514685061906174114"
  channelName: clothing-shop-orders
  notificationType: all
