//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---- Shop ----

func (in *Shop) DeepCopyInto(out *Shop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Shop) DeepCopy() *Shop {
	if in == nil {
		return nil
	}
	out := new(Shop)
	in.DeepCopyInto(out)
	return out
}

func (in *Shop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ShopList) DeepCopyInto(out *ShopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Shop, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *ShopList) DeepCopy() *ShopList {
	if in == nil {
		return nil
	}
	out := new(ShopList)
	in.DeepCopyInto(out)
	return out
}

func (in *ShopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ShopSpec) DeepCopyInto(out *ShopSpec) {
	*out = *in
	out.WalletRef = in.WalletRef
	if in.Replicas != nil {
		out.Replicas = new(int32)
		*out.Replicas = *in.Replicas
	}
}

func (in *ShopSpec) DeepCopy() *ShopSpec {
	if in == nil {
		return nil
	}
	out := new(ShopSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ShopStatus) DeepCopyInto(out *ShopStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *ShopStatus) DeepCopy() *ShopStatus {
	if in == nil {
		return nil
	}
	out := new(ShopStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- DiscordChannel ----

func (in *DiscordChannel) DeepCopyInto(out *DiscordChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DiscordChannel) DeepCopy() *DiscordChannel {
	if in == nil {
		return nil
	}
	out := new(DiscordChannel)
	in.DeepCopyInto(out)
	return out
}

func (in *DiscordChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiscordChannelList) DeepCopyInto(out *DiscordChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]DiscordChannel, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *DiscordChannelList) DeepCopy() *DiscordChannelList {
	if in == nil {
		return nil
	}
	out := new(DiscordChannelList)
	in.DeepCopyInto(out)
	return out
}

func (in *DiscordChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiscordChannelSpec) DeepCopyInto(out *DiscordChannelSpec) {
	*out = *in
}

func (in *DiscordChannelSpec) DeepCopy() *DiscordChannelSpec {
	if in == nil {
		return nil
	}
	out := new(DiscordChannelSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DiscordChannelStatus) DeepCopyInto(out *DiscordChannelStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *DiscordChannelStatus) DeepCopy() *DiscordChannelStatus {
	if in == nil {
		return nil
	}
	out := new(DiscordChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- Wallet ----

func (in *Wallet) DeepCopyInto(out *Wallet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Wallet) DeepCopy() *Wallet {
	if in == nil {
		return nil
	}
	out := new(Wallet)
	in.DeepCopyInto(out)
	return out
}

func (in *Wallet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WalletList) DeepCopyInto(out *WalletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Wallet, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *WalletList) DeepCopy() *WalletList {
	if in == nil {
		return nil
	}
	out := new(WalletList)
	in.DeepCopyInto(out)
	return out
}

func (in *WalletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WalletSpec) DeepCopyInto(out *WalletSpec) {
	*out = *in
}

func (in *WalletSpec) DeepCopy() *WalletSpec {
	if in == nil {
		return nil
	}
	out := new(WalletSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WalletStatus) DeepCopyInto(out *WalletStatus) {
	*out = *in
	if in.EncryptedPrivateKeyRef != nil {
		out.EncryptedPrivateKeyRef = new(corev1.SecretKeySelector)
		(*in).EncryptedPrivateKeyRef.DeepCopyInto(out.EncryptedPrivateKeyRef)
	}
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *WalletStatus) DeepCopy() *WalletStatus {
	if in == nil {
		return nil
	}
	out := new(WalletStatus)
	in.DeepCopyInto(out)
	return out
}
